print('A Roman soldier walks into a bar. He orders a martinus. What does the bartender say? Ask me!')
input()
print('Bartender: Don\'t you mean a martini? Soldier: If I wanted a double, I would\'ve asked for one!')
print('Do you find that funny?')
input()
print('Here\'s another!')
print('What do you call a person who quits a diet?')
input()
print('A desserter!')
print('You like?')
input()
print('Here\'s the last one!')
print('The KGB busts into a dissident\'s house. The man is in the bathroom and says "Wait a minute! At least let me finish this first!" What do the agents say?')
input()
print('We\'re kinda Russian so just hope you\'re not Stalin!')
print('I hope you enjoyed!')
